
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Administrator\Documents\Coding\Python\New folder\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("320x568")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 568,
    width = 320,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    162.99998474121094,
    283.99998474121094,
    image=image_image_1
)

canvas.create_text(
    121.99999237060547,
    260.0,
    anchor="nw",
    text="50%",
    fill="#6F6F6F",
    font=("Inter Medium", 40 * -1)
)

canvas.create_text(
    13.0,
    105.0,
    anchor="nw",
    text="November 12, 2024",
    fill="#414141",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    13.0,
    65.0,
    anchor="nw",
    text="Keep Going!",
    fill="#000000",
    font=("Inter SemiBold", 30 * -1)
)

canvas.create_text(
    28.0,
    435.0,
    anchor="nw",
    text="1,220 Days ",
    fill="#000000",
    font=("Inter Medium", 12 * -1)
)

canvas.create_text(
    186.0,
    437.0,
    anchor="nw",
    text="Remaining: 743",
    fill="#6E6E6E",
    font=("Inter Medium", 11 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    159.0,
    465.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    162.0,
    500.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=8.0,
    y=512.0,
    width=304.0,
    height=44.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    22.0,
    22.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    297.0,
    22.0,
    image=image_image_5
)
window.resizable(False, False)
window.mainloop()
