
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Administrator\Documents\Coding\Python\s\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("320x568")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 568,
    width = 320,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=9.0,
    y=517.0,
    width=304.0,
    height=44.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=10.0,
    y=264.0,
    width=304.0,
    height=66.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=10.0,
    y=342.0,
    width=304.0,
    height=66.0
)

canvas.create_text(
    29.0,
    379.0,
    anchor="nw",
    text="Complete examination for CMSC 130",
    fill="#7E7E7E",
    font=("Inter", 10 * -1)
)

canvas.create_text(
    29.0,
    355.0,
    anchor="nw",
    text="Examination",
    fill="#BF5353",
    font=("Inter Medium", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    185.0,
    243.99999973773168,
    image=image_image_1
)

canvas.create_text(
    132.0,
    236.0,
    anchor="nw",
    text="See Stats",
    fill="#B2B2B2",
    font=("Inter Medium", 10 * -1)
)

canvas.create_text(
    18.0,
    83.0,
    anchor="nw",
    text="273",
    fill="#000000",
    font=("Inter SemiBold", 80 * -1)
)

canvas.create_text(
    169.0,
    139.0,
    anchor="nw",
    text="tasks",
    fill="#000000",
    font=("Inter Light", 22 * -1)
)

canvas.create_text(
    22.0,
    75.0,
    anchor="nw",
    text="You completed",
    fill="#000000",
    font=("Inter", 14 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    160.0,
    205.0,
    image=image_image_2
)

canvas.create_text(
    47.846160888671875,
    197.88990783691406,
    anchor="nw",
    text="Day",
    fill="#A4ADBD",
    font=("HKGrotesk Medium", 11 * -1)
)

canvas.create_text(
    248.15386962890625,
    197.88990783691406,
    anchor="nw",
    text="Yearly",
    fill="#A4ADBD",
    font=("HKGrotesk Medium", 11 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=104.49542236328125,
    y=188.0,
    width=110.09174346923828,
    height=35.96330261230469
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    160.0,
    505.0,
    image=image_image_3
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=10.0,
    y=420.0,
    width=304.0,
    height=66.0
)

canvas.create_text(
    29.0,
    433.0,
    anchor="nw",
    text="Evaluation",
    fill="#7BBF53",
    font=("Inter Medium", 16 * -1)
)

canvas.create_text(
    29.0,
    457.0,
    anchor="nw",
    text="Submit evaluation sheet for Ethics 1",
    fill="#7E7E7E",
    font=("Inter", 10 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    297.0,
    22.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    296.80804443359375,
    21.8035888671875,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    21.333333492279053,
    22.208343505859375,
    image=image_image_6
)
window.resizable(False, False)
window.mainloop()
