
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Administrator\Documents\Coding\Python\s\wewe\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("320x568")
window.configure(bg = "#DC7373")


canvas = Canvas(
    window,
    bg = "#DC7373",
    height = 568,
    width = 320,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    61.0,
    320.0,
    568.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=8.0,
    y=508.0,
    width=304.0,
    height=44.0
)

canvas.create_text(
    124.0,
    518.0,
    anchor="nw",
    text="Start Timer",
    fill="#FFFFFF",
    font=("HankenGrotesk Bold", 15 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    160.0,
    502.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    157.0,
    317.0,
    image=image_image_2
)

canvas.create_text(
    48.0,
    93.0,
    anchor="nw",
    text="29:32",
    fill="#000000",
    font=("Inter SemiBold", 60 * -1)
)

canvas.create_text(
    106.0,
    160.0,
    anchor="nw",
    text="2 Breaks Remaining",
    fill="#6E6E6E",
    font=("Inter Medium", 10 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    160.0,
    31.981651306152344,
    image=entry_image_1
)

canvas.create_text(
    99.0,
    24.0,
    anchor="nw",
    text="Task Name",
    fill="#A4ADBD",
    font=("HankenGrotesk Medium", 13 * -1)
)
window.resizable(False, False)
window.mainloop()
